# Generated by Django 4.1.4 on 2022-12-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_receipt_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='person_email',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='person_name',
        ),
    ]
