# Generated by Django 4.1.4 on 2022-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_receipt_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='reimbursed',
            field=models.BooleanField(default=False),
        ),
    ]
