# Generated by Django 4.1.4 on 2022-12-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_receipt_reimbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
