# Generated by Django 4.1.4 on 2022-12-27 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0008_receipt_email_receipt_iban_receipt_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
