# Generated by Django 4.1.4 on 2022-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0009_receipt_status_updated_at_receipt_status_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
